#!/usr/bin/env python3
"""PIO pre-build hook: embed firmware-signed.bin into the wisp build.

Wired from software/wisp/platformio.ini as
  extra_scripts = pre:../../scripts/embed_firmware.py
inside [env:seeed_xiao_esp32_c6]. PIO passes the build env via
Import("env"). The hook runs BEFORE compile so the generated header is
on disk before the wisp's #include directives are resolved.

Input:  software/lamp-os/.pio/build/upesy_wroom/firmware-signed.bin
Output: software/wisp/include/embedded_firmware_generated.h
        (gitignored — see .gitignore at repo root)

The generated header declares:
  namespace wisp {
  constexpr uint8_t kEmbeddedFirmware[N] = { ... };
  constexpr size_t  kEmbeddedFirmwareLen = sizeof(kEmbeddedFirmware);
  }

The wisp's existing software/wisp/include/embedded_firmware.h uses
`__has_include("embedded_firmware_generated.h")` to pick between this
generated header and the committed stub at embedded_firmware.h.stub.

Staleness check: content-based. The generated header's first line
embeds the sha256 of the source bytes; if that hex matches the current
firmware-signed.bin's sha256, regeneration is skipped. This avoids
re-emitting (and forcing a wisp recompile of) the 1.4 MB byte array
when the lamp build didn't change.

Missing-input behaviour:
  - Default: fail the wisp build with a clear next-step message.
  - WISP_ALLOW_STUB_FIRMWARE=1: emit 200 bytes of 0xFF as a stub. The
    LSIG magic is intentionally absent, so FirmwareCarrier::begin()
    rejects the blob and the distributor stays Disabled. Wisp's
    palette/aurora work continues normally.
"""

from __future__ import annotations

import hashlib
import os
import struct
import sys
from pathlib import Path

PRIVATE_KEY_PATH = Path.home() / ".lamp-os-firmware-key.bin"
DEFAULT_LAMP_ENV = "upesy_wroom"

# Same path-resolution dance as sign_firmware.py — SCons exec() doesn't
# define __file__.

REPO_ROOT: Path
LAMP_BIN_PATH: Path
WISP_GENERATED_HEADER: Path


def _resolve_paths_cli() -> None:
    global REPO_ROOT, LAMP_BIN_PATH, WISP_GENERATED_HEADER
    script_dir = Path(__file__).resolve().parent
    REPO_ROOT = script_dir.parent
    _populate_dependent_paths()


def _resolve_paths_pio(env) -> None:
    global REPO_ROOT
    project_dir = Path(env.subst("$PROJECT_DIR")).resolve()
    # PROJECT_DIR is software/wisp; repo root is its parent's parent.
    REPO_ROOT = project_dir.parent.parent
    _populate_dependent_paths()


def _populate_dependent_paths() -> None:
    global LAMP_BIN_PATH, WISP_GENERATED_HEADER
    lamp_env = os.environ.get("LAMP_ENV", DEFAULT_LAMP_ENV)
    LAMP_BIN_PATH = (
        REPO_ROOT
        / "software"
        / "lamp-os"
        / ".pio"
        / "build"
        / lamp_env
        / "firmware-signed.bin"
    )
    WISP_GENERATED_HEADER = (
        REPO_ROOT / "software" / "wisp" / "include" / "embedded_firmware_generated.h"
    )


LSIG_FOOTER_LEN = 96
STUB_BYTES = bytes([0xFF] * 200)


def _format_blob(blob: bytes) -> str:
    """16 bytes per line for readable git diffs (though the file is gitignored).

    Each row: 16 hex bytes separated by `, `, indented with two spaces,
    with a trailing comma. The last row's trailing comma is preserved
    (C++ allows it; keeps diff churn down when the blob grows by one).
    """
    out_lines = []
    for row_start in range(0, len(blob), 16):
        row = blob[row_start : row_start + 16]
        hex_row = ", ".join(f"0x{b:02x}" for b in row)
        out_lines.append(f"  {hex_row},")
    return "\n".join(out_lines)


def _parse_footer(blob: bytes) -> tuple[str, str] | None:
    """Pull channel + version out for the build-log line. None on bad blob."""
    if len(blob) < LSIG_FOOTER_LEN:
        return None
    footer = blob[-LSIG_FOOTER_LEN:]
    if footer[0:4] != b"LSIG":
        return None
    channel = footer[4:12].rstrip(b"\x00").decode("ascii", errors="replace")
    packed = struct.unpack_from("<I", footer, 12)[0]
    version_str = f"{(packed >> 16) & 0xFF}.{(packed >> 8) & 0xFF}.{packed & 0xFF}"
    return channel, version_str


def _existing_sha(header_path: Path) -> str | None:
    """Return the embedded source sha256 if the header has the marker."""
    if not header_path.exists():
        return None
    try:
        with open(header_path, "r") as fh:
            for line in fh:
                # Marker line written by _render: "// source sha256: <hex>"
                if line.startswith("// source sha256:"):
                    return line.split(":", 1)[1].strip()
                if not line.startswith("//"):
                    break
    except OSError:
        return None
    return None


def _render(blob: bytes, source_sha_hex: str, banner: str) -> str:
    return (
        f"// AUTO-GENERATED by scripts/embed_firmware.py — DO NOT EDIT.\n"
        f"// source sha256: {source_sha_hex}\n"
        f"// {banner}\n"
        f"#pragma once\n"
        f"\n"
        f"#include <cstddef>\n"
        f"#include <cstdint>\n"
        f"\n"
        f"namespace wisp {{\n"
        f"\n"
        f"constexpr uint8_t kEmbeddedFirmware[] = {{\n"
        f"{_format_blob(blob)}\n"
        f"}};\n"
        f"constexpr size_t kEmbeddedFirmwareLen = sizeof(kEmbeddedFirmware);\n"
        f"\n"
        f"}}  // namespace wisp\n"
    )


def _write_header(blob: bytes, header_path: Path, banner: str) -> bool:
    """Write the generated header if stale. Returns True iff it was rewritten."""
    sha_hex = hashlib.sha256(blob).hexdigest()
    existing = _existing_sha(header_path)
    if existing == sha_hex:
        print(
            f"[embed] up-to-date: {header_path.name} (sha256={sha_hex[:16]}...)"
        )
        return False

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(_render(blob, sha_hex, banner))
    print(
        f"[embed] wrote {header_path.name}: {len(blob)} bytes "
        f"(sha256={sha_hex[:16]}...)"
    )
    return True


def embed() -> None:
    if not LAMP_BIN_PATH.exists():
        if os.environ.get("WISP_ALLOW_STUB_FIRMWARE") == "1":
            print(
                f"[embed] WARNING: {LAMP_BIN_PATH} missing — emitting stub blob.\n"
                f"[embed]          FirmwareCarrier will stay Disabled at runtime;\n"
                f"[embed]          wisp continues palette work as normal.",
                file=sys.stderr,
            )
            _write_header(
                STUB_BYTES,
                WISP_GENERATED_HEADER,
                "stub blob — 200 bytes of 0xFF, no LSIG magic (carrier disabled)",
            )
            return
        print(
            f"[embed] FATAL: signed lamp firmware not found:\n"
            f"          {LAMP_BIN_PATH}\n"
            f"\n"
            f"        Run `cd software/lamp-os && pio run -e upesy_wroom` first\n"
            f"        to build + sign the lamp firmware, OR set\n"
            f"        WISP_ALLOW_STUB_FIRMWARE=1 to build the wisp with a\n"
            f"        placeholder (distributor will stay Disabled at runtime).",
            file=sys.stderr,
        )
        sys.exit(1)

    blob = LAMP_BIN_PATH.read_bytes()
    parsed = _parse_footer(blob)
    if parsed is None:
        print(
            f"[embed] FATAL: {LAMP_BIN_PATH} does not look like a signed lamp\n"
            f"        firmware (LSIG footer missing or short). Did the lamp\n"
            f"        post-build hook run? Try a clean rebuild.",
            file=sys.stderr,
        )
        sys.exit(1)
    channel, version = parsed

    banner = (
        f"channel={channel} version={version} "
        f"blob={len(blob)}B (signed_region+96B footer)"
    )
    _write_header(blob, WISP_GENERATED_HEADER, banner)


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------


def _pre_build_action():
    embed()


try:
    Import("env")  # type: ignore[name-defined]
    _resolve_paths_pio(env)  # type: ignore[name-defined]
    # Pre-action against the program target: PIO runs SCons targets in
    # dependency order, so making the header a sideeffect of "before the
    # program target builds" ensures it exists by the time the wisp's
    # source files compile.
    #
    # Simpler still: call embed() directly at script-load time. PIO's
    # `pre:` prefix already guarantees the script runs before compilation;
    # nothing in the env affects what we write.
    embed()
except NameError:
    if __name__ == "__main__":
        _resolve_paths_cli()
        embed()
